name: {{ cookiecutter.project_name }}
plugins:
  - name: vyper
{%- if cookiecutter.ERC4626 == "y" %}
  - name: hardhat
  - name: alchemy
  - name: etherscan

# if you installed hardhat for the first time
# cd into your {{cookiecutter.project_name}} 
# npm install --save-dev hardhat

ethereum:
  default_network: mainnet-fork

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

{%- endif %}