on: ["push", "pull_request"]

name: Test

jobs:
  validate-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
        - Basic
        - Burnable
        - Permitable
        - Mintable
        - ERC4626
    steps:
    - uses: actions/checkout@v2
    - uses: ApeWorX/github-action@v1
    - run: pip install --upgrade pip
    - run: pip install eip712
    - run: ape plugins install -U template
    - run: ape template . --replay-file tests/${{ matrix.template }}.json
    - name: Install plugins
      run: |
        cd ${{ matrix.template }}
        ape plugins install -U .
    - name: install additional dependencies
      if: ${{ matrix.template == 'ERC4626' }}
      run: npm install --save-dev hardhat
    - name: Compile contracts
      run: |
        cd ${{ matrix.template }}
        ape compile --size
    - name: Run tests
      env:
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        WEB3_ALCHEMY_PROJECT_ID: ${{ secrets.WEB3_ALCHEMY_PROJECT_ID }} 
      run: |
        cd ${{ matrix.template }}
        ape test -s
